import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { InputText } from 'primereact/inputtext';
import { InputNumber } from 'primereact/inputnumber';
import { Dropdown } from 'primereact/dropdown';
import { Checkbox } from 'primereact/checkbox';
import type { IncomeEvent } from '../types/IncomeEvent';
import { confirmDialog } from 'primereact/confirmdialog';
import { spacing, colors, fontSize, border, dialogWidth } from '../styles/theme';
import { eventTypeIcons } from '../utils/defaultName';
import { buildAgeOptions } from '../utils/ageOptions';
import { resolveOwnerAge } from '../utils/ownerAge';

const Form = styled.form`
  display: flex;
  flex-direction: column;
  gap: ${spacing.md};
  padding: ${spacing.sm} 0;

  .p-inputtext,
  .p-dropdown,
  .p-inputnumber {
    width: 100%;
  }
`;

const InputGroup = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${spacing.xs};
`;

const AmountRow = styled.div`
  display: grid;
  grid-template-columns: 1fr 9rem;
  gap: ${spacing.sm};
  align-items: start;
`;

const CheckboxGroup = styled.div`
  display: flex;
  align-items: center;
  gap: ${spacing.sm};
`;

const HelpText = styled.small`
  color: ${colors.textMuted};
  font-size: ${fontSize.xs};
`;

const WarningText = styled.small`
  color: ${colors.danger};
  font-size: ${fontSize.xs};
`;

const TrashButton = styled.button`
  background: none;
  border: none;
  cursor: pointer;
  padding: ${spacing.xs};
  border-radius: ${border.radius};
  color: ${colors.danger};
  font-size: ${fontSize.xl};
  line-height: 1;
  display: flex;
  align-items: center;

  &:hover {
    color: ${colors.dangerHover};
    background: ${colors.bgMedium};
  }
`;

const AdvancedToggle = styled.button`
  background: none;
  border: none;
  border-top: ${border.light};
  padding: ${spacing.sm} 0 0 0;
  margin-top: ${spacing.xs};
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: ${spacing.sm};
  color: ${colors.textMuted};
  font-size: ${fontSize.sm};
  text-align: left;
  width: 100%;

  &:hover {
    color: ${colors.textPrimary};
  }

  i {
    font-size: ${fontSize.xs};
  }
`;

const AdvancedBody = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${spacing.md};
  margin-top: ${spacing.sm};
`;

interface SocialSecurityDialogProps {
  visible: boolean;
  onHide: () => void;
  onSave: (event: Omit<IncomeEvent, 'id'>) => void;
  onDelete?: () => void;
  editEvent?: IncomeEvent;
  filingStatus: 'single' | 'mfs' | 'mfj' | 'hoh';
  existingSSEvents: IncomeEvent[];
  currentAge: number;
  spouseAge: number | null;
  referenceYear: number;
}

/** Check if a name matches an auto-generated SS pattern */
export function isAutoGeneratedSSName(name: string): boolean {
  return /^Social Security( \d+| \(.+\))?$/.test(name);
}

/** Generate an owner-based SS default name */
export function generateSSDefaultName(owner: 'self' | 'spouse'): string {
  return owner === 'spouse' ? 'Social Security (Spouse)' : 'Social Security (Self)';
}

const makeDefaultFormData = () => ({
  name: '',
  owner: 'self' as 'self' | 'spouse',
  displayAmount: 0,
  amountPeriod: 'monthly' as 'monthly' | 'annual',
  startAge: 67,
  ssAmountBasis: 'today' as 'today' | 'future',
  ssHaircutEnabled: true,
  ssHaircutPercent: 23,
});

const SocialSecurityDialog: React.FC<SocialSecurityDialogProps> = ({
  visible,
  onHide,
  onSave,
  onDelete,
  editEvent,
  filingStatus,
  existingSSEvents,
  currentAge,
  spouseAge,
  referenceYear,
}) => {
  const isEditing = !!editEvent;
  const [formData, setFormData] = useState(makeDefaultFormData());
  const [advancedOpen, setAdvancedOpen] = useState(false);

  const isMfj = filingStatus === 'mfj';

  // Determine which owner slots are already taken (excluding the event being edited)
  const takenOwners = existingSSEvents
    .filter((e) => !editEvent || e.id !== editEvent.id)
    .map((e) => e.owner ?? 'self');

  const selfTaken = takenOwners.includes('self');
  const spouseTaken = takenOwners.includes('spouse');

  // Calculate the start year based on owner's age
  const ownerAge = resolveOwnerAge(formData.owner, currentAge, spouseAge);
  const missingSpouseAge = formData.owner === 'spouse' && spouseAge === null;

  // Build start age dropdown options showing age + year
  const startAgeOptions = buildAgeOptions(referenceYear, ownerAge, 62, 120);

  useEffect(() => {
    if (!visible) return;
    setAdvancedOpen(false);
    if (editEvent) {
      const period = editEvent.amountPeriod ?? 'annual';
      const displayAmount = period === 'monthly' ? editEvent.amount / 12 : editEvent.amount;
      setFormData({
        name: editEvent.name,
        owner: editEvent.owner ?? 'self',
        displayAmount,
        amountPeriod: period,
        startAge: editEvent.startAge,
        ssAmountBasis: editEvent.ssAmountBasis ?? 'today',
        ssHaircutEnabled: editEvent.ssHaircutEnabled !== false,
        ssHaircutPercent: editEvent.ssHaircutPercent ?? 23,
      });
    } else {
      const defaultOwner: 'self' | 'spouse' = isMfj && selfTaken && !spouseTaken ? 'spouse' : 'self';
      const ownerStartAge = defaultOwner === 'spouse' && spouseAge !== null ? spouseAge : currentAge;
      const defaults = {
        ...makeDefaultFormData(),
        owner: defaultOwner,
        name: generateSSDefaultName(defaultOwner),
        startAge: Math.max(62, ownerStartAge),
      };
      setFormData(defaults);
    }
  }, [visible, editEvent, isMfj, selfTaken, spouseTaken, existingSSEvents]);

  const handleOwnerChange = (newOwner: 'self' | 'spouse') => {
    const updates: Partial<ReturnType<typeof makeDefaultFormData>> = { owner: newOwner };
    // Auto-update name if it's still an auto-generated one
    if (isAutoGeneratedSSName(formData.name)) {
      updates.name = generateSSDefaultName(newOwner);
    }
    setFormData({ ...formData, ...updates });
  };

  const handlePeriodChange = (newPeriod: 'monthly' | 'annual') => {
    if (newPeriod === formData.amountPeriod) return;
    const converted = newPeriod === 'monthly'
      ? formData.displayAmount / 12
      : formData.displayAmount * 12;
    setFormData({
      ...formData,
      amountPeriod: newPeriod,
      displayAmount: Math.round(converted * 100) / 100,
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const annualAmount = formData.amountPeriod === 'monthly'
      ? formData.displayAmount * 12
      : formData.displayAmount;
    onSave({
      type: 'social_security',
      name: formData.name,
      owner: isMfj ? formData.owner : 'self',
      amount: annualAmount,
      startAge: formData.startAge,
      taxStatus: 'before_tax',
      colaType: 'inflation_adjusted',
      ssAmountBasis: formData.ssAmountBasis,
      ssHaircutEnabled: formData.ssHaircutEnabled,
      ssHaircutPercent: formData.ssHaircutPercent,
      amountPeriod: formData.amountPeriod,
    });
    onHide();
  };

  const amountBasisOptions = [
    { label: "Today's Dollars", value: 'today' },
    { label: 'Adjusted for Future Inflation', value: 'future' },
  ];

  const periodOptions = [
    { label: 'Monthly', value: 'monthly' },
    { label: 'Annual', value: 'annual' },
  ];

  const ownerOptions = [
    { label: 'Self', value: 'self', disabled: selfTaken },
    { label: 'Spouse', value: 'spouse', disabled: spouseTaken },
  ];

  const dialogFooter = (
    <div>
      <Button
        label='Cancel'
        icon='pi pi-times'
        onClick={onHide}
        className='p-button-text'
      />
      <Button
        label={isEditing ? 'Save Changes' : 'Add Event'}
        icon='pi pi-check'
        onClick={handleSubmit}
        disabled={missingSpouseAge}
        type='submit'
      />
    </div>
  );

  const handleDeleteClick = () => {
    confirmDialog({
      message: `Are you sure you want to delete "${formData.name}"?`,
      header: 'Confirm Delete',
      icon: 'pi pi-exclamation-triangle',
      accept: onDelete,
    });
  };

  return (
    <Dialog
      header={
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
          <span>
            <i className={eventTypeIcons['social_security']} style={{ marginRight: spacing.sm, color: colors.primary }} />
            {isEditing ? 'Edit Social Security' : 'Add Social Security'}
          </span>
          {onDelete && (
            <TrashButton onClick={handleDeleteClick} title="Delete">
              <i className="pi pi-trash" />
            </TrashButton>
          )}
        </div>
      }
      visible={visible}
      style={dialogWidth('32rem')}
      onHide={onHide}
      closable={false}
      closeOnEscape={true}
      footer={dialogFooter}
    >
      <Form onSubmit={handleSubmit}>
        <InputGroup>
          <label>Name</label>
          <InputText
            value={formData.name}
            onChange={(e) =>
              setFormData({ ...formData, name: e.target.value })
            }
            required
          />
        </InputGroup>

        {isMfj && (
          <InputGroup>
            <label>Recipient</label>
            <Dropdown
              value={formData.owner}
              options={ownerOptions}
              onChange={(e) => handleOwnerChange(e.value)}
            />
          </InputGroup>
        )}

        <InputGroup>
          <label>Benefit Amount</label>
          <AmountRow>
            <InputNumber
              value={formData.displayAmount}
              onValueChange={(e) =>
                setFormData({ ...formData, displayAmount: e.value || 0 })
              }
              mode='currency'
              currency='USD'
              required
            />
            <Dropdown
              value={formData.amountPeriod}
              options={periodOptions}
              onChange={(e) => handlePeriodChange(e.value)}
            />
          </AmountRow>
        </InputGroup>

        <InputGroup>
          <label>Amount is in</label>
          <Dropdown
            value={formData.ssAmountBasis}
            options={amountBasisOptions}
            onChange={(e) => setFormData({ ...formData, ssAmountBasis: e.value })}
          />
          <HelpText>
            {formData.ssAmountBasis === 'future'
              ? 'Projected nominal amount at claiming age — COLA applied after claiming'
              : 'Amount from your SSA statement — will be adjusted for inflation'}
          </HelpText>
        </InputGroup>

        <InputGroup>
          <label>Start Age</label>
          <Dropdown
            value={formData.startAge}
            options={startAgeOptions}
            onChange={(e) => setFormData({ ...formData, startAge: e.value })}
          />
          {missingSpouseAge && (
            <WarningText>Set spouse age in scenario to show correct years</WarningText>
          )}
        </InputGroup>

        <AdvancedToggle
          type='button'
          onClick={() => setAdvancedOpen((v) => !v)}
          aria-expanded={advancedOpen}
        >
          <i className={advancedOpen ? 'pi pi-chevron-down' : 'pi pi-chevron-right'} />
          Advanced
        </AdvancedToggle>

        {advancedOpen && (
          <AdvancedBody>
            <CheckboxGroup>
              <Checkbox
                inputId='ssHaircutEnabled'
                checked={formData.ssHaircutEnabled}
                onChange={(e) =>
                  setFormData({ ...formData, ssHaircutEnabled: e.checked || false })
                }
              />
              <label htmlFor='ssHaircutEnabled'>
                Apply trust fund reduction (from 2034)
              </label>
            </CheckboxGroup>

            {formData.ssHaircutEnabled && (
              <InputGroup>
                <label>Reduction Percentage</label>
                <InputNumber
                  value={formData.ssHaircutPercent}
                  onValueChange={(e) =>
                    setFormData({ ...formData, ssHaircutPercent: e.value ?? 23 })
                  }
                  suffix='%'
                  min={0}
                  max={100}
                />
                <HelpText>
                  Current trustees estimate: 23% reduction when trust fund is exhausted
                </HelpText>
              </InputGroup>
            )}
          </AdvancedBody>
        )}
      </Form>
    </Dialog>
  );
};

export default SocialSecurityDialog;
