import { describe, it, expect } from 'vitest';
import { isAutoGeneratedSSName, generateSSDefaultName, resolveOwnerAge } from './SocialSecurityDialog';

describe('isAutoGeneratedSSName', () => {
  it('matches old numbered format', () => {
    expect(isAutoGeneratedSSName('Social Security 1')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security 2')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security 99')).toBe(true);
  });

  it('matches new owner-based format', () => {
    expect(isAutoGeneratedSSName('Social Security (Self)')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security (Jane)')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security (Spouse)')).toBe(true);
  });

  it('matches bare "Social Security"', () => {
    expect(isAutoGeneratedSSName('Social Security')).toBe(true);
  });

  it('does not match custom names', () => {
    expect(isAutoGeneratedSSName('My SS Benefit')).toBe(false);
    expect(isAutoGeneratedSSName("John's Social Security"  )).toBe(false);
    expect(isAutoGeneratedSSName('')).toBe(false);
    expect(isAutoGeneratedSSName('social security (Self)')).toBe(false); // case-sensitive
  });
});

describe('generateSSDefaultName', () => {
  it('generates self name', () => {
    expect(generateSSDefaultName('self')).toBe('Social Security (Self)');
  });

  it('generates spouse name', () => {
    expect(generateSSDefaultName('spouse')).toBe('Social Security (Spouse)');
  });
});

describe('resolveOwnerAge', () => {
  it('returns currentAge for self owner', () => {
    expect(resolveOwnerAge('self', 65, 60)).toBe(65);
  });

  it('returns spouseAge for spouse owner when spouseAge is set', () => {
    expect(resolveOwnerAge('spouse', 65, 60)).toBe(60);
  });

  it('falls back to currentAge for spouse owner when spouseAge is null', () => {
    expect(resolveOwnerAge('spouse', 65, null)).toBe(65);
  });

  it('returns currentAge for self owner even when spouseAge is null', () => {
    expect(resolveOwnerAge('self', 70, null)).toBe(70);
  });
});

describe('monthly/annual conversion logic', () => {
  it('monthly to annual: multiply by 12', () => {
    const monthlyAmount = 2000;
    const annualAmount = monthlyAmount * 12;
    expect(annualAmount).toBe(24000);
  });

  it('annual to monthly: divide by 12', () => {
    const annualAmount = 24000;
    const monthlyAmount = annualAmount / 12;
    expect(monthlyAmount).toBe(2000);
  });

  it('handles non-round monthly amounts', () => {
    const monthlyAmount = 2341;
    const annualAmount = monthlyAmount * 12;
    expect(annualAmount).toBe(28092);
    // Round-trip: annual back to monthly
    expect(annualAmount / 12).toBe(2341);
  });

  it('rounds display amount on period toggle to avoid floating point noise', () => {
    // Simulate: user enters $2500 annual, toggles to monthly
    const annual = 2500;
    const monthly = Math.round((annual / 12) * 100) / 100;
    expect(monthly).toBe(208.33);
    // Toggle back to annual
    const backToAnnual = Math.round(monthly * 12 * 100) / 100;
    expect(backToAnnual).toBe(2499.96); // small rounding difference is expected
  });

  it('re-edit restores monthly display amount from stored annual', () => {
    // User saved $2000/month → stored as $24000 annual with amountPeriod: 'monthly'
    const storedAmount = 24000;
    const storedPeriod = 'monthly';
    const displayAmount = storedPeriod === 'monthly' ? storedAmount / 12 : storedAmount;
    expect(displayAmount).toBe(2000);
  });

  it('re-edit shows annual amount when amountPeriod is annual', () => {
    const storedAmount = 30000;
    // Annual period means display amount equals stored amount (no division)
    expect(storedAmount).toBe(30000);
  });
});
