import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { InputText } from 'primereact/inputtext';
import { InputNumber } from 'primereact/inputnumber';
import { Dropdown } from 'primereact/dropdown';
import { Checkbox } from 'primereact/checkbox';
import type { IncomeEvent } from '../types/IncomeEvent';
import { spacing, colors, fontSize } from '../styles/theme';

const Form = styled.form`
  display: flex;
  flex-direction: column;
  gap: ${spacing.md};
  padding: ${spacing.sm} 0;

  .p-inputtext,
  .p-dropdown,
  .p-inputnumber {
    width: 100%;
  }
`;

const InputGroup = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${spacing.xs};
`;

const FieldRow = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: ${spacing.md};
`;

const AmountRow = styled.div`
  display: grid;
  grid-template-columns: 1fr 9rem;
  gap: ${spacing.sm};
  align-items: start;
`;

const CheckboxGroup = styled.div`
  display: flex;
  align-items: center;
  gap: ${spacing.sm};
`;

const HelpText = styled.small`
  color: ${colors.textMuted};
  font-size: ${fontSize.xs};
`;

const WarningText = styled.small`
  color: ${colors.danger};
  font-size: ${fontSize.xs};
`;

interface SocialSecurityDialogProps {
  visible: boolean;
  onHide: () => void;
  onSave: (event: Omit<IncomeEvent, 'id'>) => void;
  editEvent?: IncomeEvent;
  filingStatus: 'single' | 'mfs' | 'mfj' | 'hoh';
  spouseName: string | null;
  existingSSEvents: IncomeEvent[];
  currentAge: number;
  spouseAge: number | null;
  referenceYear: number;
}

/** Resolve the effective age for an SS event owner */
export function resolveOwnerAge(
  owner: 'self' | 'spouse',
  currentAge: number,
  spouseAge: number | null,
): number {
  return owner === 'spouse' && spouseAge !== null ? spouseAge : currentAge;
}

/** Build start-age dropdown options (62–120) with year labels */
export function buildStartAgeOptions(
  referenceYear: number,
  ownerAge: number,
): { label: string; value: number }[] {
  return Array.from({ length: 120 - 62 + 1 }, (_, i) => {
    const age = 62 + i;
    const year = referenceYear + (age - ownerAge);
    return { label: `${age} (${year})`, value: age };
  });
}

/** Check if a name matches an auto-generated SS pattern */
export function isAutoGeneratedSSName(name: string): boolean {
  return /^Social Security( \d+| \(.+\))?$/.test(name);
}

/** Generate an owner-based SS default name */
export function generateSSDefaultName(owner: 'self' | 'spouse', spouseName: string | null): string {
  if (owner === 'spouse') {
    return `Social Security (${spouseName || 'Spouse'})`;
  }
  return 'Social Security (Self)';
}

const makeDefaultFormData = () => ({
  name: '',
  owner: 'self' as 'self' | 'spouse',
  displayAmount: 0,
  amountPeriod: 'monthly' as 'monthly' | 'annual',
  startAge: 67,
  ssAmountBasis: 'today' as 'today' | 'future',
  ssHaircutEnabled: true,
  ssHaircutPercent: 23,
});

const SocialSecurityDialog: React.FC<SocialSecurityDialogProps> = ({
  visible,
  onHide,
  onSave,
  editEvent,
  filingStatus,
  spouseName,
  existingSSEvents,
  currentAge,
  spouseAge,
  referenceYear,
}) => {
  const isEditing = !!editEvent;
  const [formData, setFormData] = useState(makeDefaultFormData());

  const isMfj = filingStatus === 'mfj';

  // Determine which owner slots are already taken (excluding the event being edited)
  const takenOwners = existingSSEvents
    .filter((e) => !editEvent || e.id !== editEvent.id)
    .map((e) => e.owner ?? 'self');

  const selfTaken = takenOwners.includes('self');
  const spouseTaken = takenOwners.includes('spouse');

  // Calculate the start year based on owner's age
  const ownerAge = resolveOwnerAge(formData.owner, currentAge, spouseAge);
  const missingSpouseAge = formData.owner === 'spouse' && spouseAge === null;

  // Build start age dropdown options showing age + year
  const startAgeOptions = buildStartAgeOptions(referenceYear, ownerAge);

  useEffect(() => {
    if (!visible) return;
    if (editEvent) {
      const period = editEvent.amountPeriod ?? 'annual';
      const displayAmount = period === 'monthly' ? editEvent.amount / 12 : editEvent.amount;
      setFormData({
        name: editEvent.name,
        owner: editEvent.owner ?? 'self',
        displayAmount,
        amountPeriod: period,
        startAge: editEvent.startAge,
        ssAmountBasis: editEvent.ssAmountBasis ?? 'today',
        ssHaircutEnabled: editEvent.ssHaircutEnabled !== false,
        ssHaircutPercent: editEvent.ssHaircutPercent ?? 23,
      });
    } else {
      const defaultOwner: 'self' | 'spouse' = isMfj && selfTaken && !spouseTaken ? 'spouse' : 'self';
      const defaults = {
        ...makeDefaultFormData(),
        owner: defaultOwner,
        name: generateSSDefaultName(defaultOwner, spouseName),
      };
      setFormData(defaults);
    }
  }, [visible, editEvent, isMfj, selfTaken, spouseTaken, existingSSEvents, spouseName]);

  const handleOwnerChange = (newOwner: 'self' | 'spouse') => {
    const updates: Partial<ReturnType<typeof makeDefaultFormData>> = { owner: newOwner };
    // Auto-update name if it's still an auto-generated one
    if (isAutoGeneratedSSName(formData.name)) {
      updates.name = generateSSDefaultName(newOwner, spouseName);
    }
    setFormData({ ...formData, ...updates });
  };

  const handlePeriodChange = (newPeriod: 'monthly' | 'annual') => {
    if (newPeriod === formData.amountPeriod) return;
    const converted = newPeriod === 'monthly'
      ? formData.displayAmount / 12
      : formData.displayAmount * 12;
    setFormData({
      ...formData,
      amountPeriod: newPeriod,
      displayAmount: Math.round(converted * 100) / 100,
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const annualAmount = formData.amountPeriod === 'monthly'
      ? formData.displayAmount * 12
      : formData.displayAmount;
    onSave({
      type: 'social_security',
      name: formData.name,
      owner: isMfj ? formData.owner : 'self',
      amount: annualAmount,
      startAge: formData.startAge,
      taxStatus: 'before_tax',
      colaType: 'inflation_adjusted',
      ssAmountBasis: formData.ssAmountBasis,
      ssHaircutEnabled: formData.ssHaircutEnabled,
      ssHaircutPercent: formData.ssHaircutPercent,
      amountPeriod: formData.amountPeriod,
    });
    onHide();
  };

  const amountBasisOptions = [
    { label: "Today's Dollars", value: 'today' },
    { label: 'Adjusted for Future Inflation', value: 'future' },
  ];

  const periodOptions = [
    { label: 'Monthly', value: 'monthly' },
    { label: 'Annual', value: 'annual' },
  ];

  const ownerOptions = [
    { label: 'Self', value: 'self', disabled: selfTaken },
    { label: spouseName || 'Spouse', value: 'spouse', disabled: spouseTaken },
  ];

  const dialogFooter = (
    <div>
      <Button
        label='Cancel'
        icon='pi pi-times'
        onClick={onHide}
        className='p-button-text'
      />
      <Button
        label={isEditing ? 'Save Changes' : 'Add Event'}
        icon='pi pi-check'
        onClick={handleSubmit}
        disabled={missingSpouseAge}
        type='submit'
      />
    </div>
  );

  return (
    <Dialog
      header={isEditing ? 'Edit Social Security' : 'Add Social Security'}
      visible={visible}
      style={{ width: '32rem' }}
      onHide={onHide}
      footer={dialogFooter}
    >
      <Form onSubmit={handleSubmit}>
        <InputGroup>
          <label>Name</label>
          <InputText
            value={formData.name}
            onChange={(e) =>
              setFormData({ ...formData, name: e.target.value })
            }
            required
          />
        </InputGroup>

        {isMfj && (
          <InputGroup>
            <label>Recipient</label>
            <Dropdown
              value={formData.owner}
              options={ownerOptions}
              onChange={(e) => handleOwnerChange(e.value)}
            />
          </InputGroup>
        )}

        <InputGroup>
          <label>Benefit Amount</label>
          <AmountRow>
            <InputNumber
              value={formData.displayAmount}
              onValueChange={(e) =>
                setFormData({ ...formData, displayAmount: e.value || 0 })
              }
              mode='currency'
              currency='USD'
              required
            />
            <Dropdown
              value={formData.amountPeriod}
              options={periodOptions}
              onChange={(e) => handlePeriodChange(e.value)}
            />
          </AmountRow>
          <HelpText>
            {formData.ssAmountBasis === 'future'
              ? 'Projected nominal amount at claiming age — COLA applied after claiming'
              : 'Amount from your SSA statement — will be adjusted for inflation'}
          </HelpText>
        </InputGroup>

        <FieldRow>
          <InputGroup>
            <label>Start Age</label>
            <Dropdown
              value={formData.startAge}
              options={startAgeOptions}
              onChange={(e) => setFormData({ ...formData, startAge: e.value })}
            />
            {missingSpouseAge && (
              <WarningText>Set spouse age in scenario to show correct years</WarningText>
            )}
          </InputGroup>

          <InputGroup>
            <label>Amount Type</label>
            <Dropdown
              value={formData.ssAmountBasis}
              options={amountBasisOptions}
              onChange={(e) => setFormData({ ...formData, ssAmountBasis: e.value })}
            />
          </InputGroup>
        </FieldRow>

        <CheckboxGroup>
          <Checkbox
            inputId='ssHaircutEnabled'
            checked={formData.ssHaircutEnabled}
            onChange={(e) =>
              setFormData({ ...formData, ssHaircutEnabled: e.checked || false })
            }
          />
          <label htmlFor='ssHaircutEnabled'>
            Apply trust fund reduction (from 2034)
          </label>
        </CheckboxGroup>

        {formData.ssHaircutEnabled && (
          <InputGroup>
            <label>Reduction Percentage</label>
            <InputNumber
              value={formData.ssHaircutPercent}
              onValueChange={(e) =>
                setFormData({ ...formData, ssHaircutPercent: e.value ?? 23 })
              }
              suffix='%'
              min={0}
              max={100}
            />
            <HelpText>
              Current trustees estimate: 23% reduction when trust fund is exhausted
            </HelpText>
          </InputGroup>
        )}
      </Form>
    </Dialog>
  );
};

export default SocialSecurityDialog;
