import { describe, it, expect } from 'vitest';
import { isAutoGeneratedSSName, generateSSDefaultName, resolveOwnerAge, buildStartAgeOptions } from './SocialSecurityDialog';

describe('isAutoGeneratedSSName', () => {
  it('matches old numbered format', () => {
    expect(isAutoGeneratedSSName('Social Security 1')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security 2')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security 99')).toBe(true);
  });

  it('matches new owner-based format', () => {
    expect(isAutoGeneratedSSName('Social Security (Self)')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security (Jane)')).toBe(true);
    expect(isAutoGeneratedSSName('Social Security (Spouse)')).toBe(true);
  });

  it('matches bare "Social Security"', () => {
    expect(isAutoGeneratedSSName('Social Security')).toBe(true);
  });

  it('does not match custom names', () => {
    expect(isAutoGeneratedSSName('My SS Benefit')).toBe(false);
    expect(isAutoGeneratedSSName("John's Social Security"  )).toBe(false);
    expect(isAutoGeneratedSSName('')).toBe(false);
    expect(isAutoGeneratedSSName('social security (Self)')).toBe(false); // case-sensitive
  });
});

describe('generateSSDefaultName', () => {
  it('generates self name', () => {
    expect(generateSSDefaultName('self', 'Jane')).toBe('Social Security (Self)');
    expect(generateSSDefaultName('self', null)).toBe('Social Security (Self)');
  });

  it('generates spouse name using spouse name', () => {
    expect(generateSSDefaultName('spouse', 'Jane')).toBe('Social Security (Jane)');
    expect(generateSSDefaultName('spouse', 'Bob Smith')).toBe('Social Security (Bob Smith)');
  });

  it('falls back to "Spouse" when no spouse name', () => {
    expect(generateSSDefaultName('spouse', null)).toBe('Social Security (Spouse)');
    expect(generateSSDefaultName('spouse', '')).toBe('Social Security (Spouse)');
  });
});

describe('resolveOwnerAge', () => {
  it('returns currentAge for self owner', () => {
    expect(resolveOwnerAge('self', 65, 60)).toBe(65);
  });

  it('returns spouseAge for spouse owner when spouseAge is set', () => {
    expect(resolveOwnerAge('spouse', 65, 60)).toBe(60);
  });

  it('falls back to currentAge for spouse owner when spouseAge is null', () => {
    expect(resolveOwnerAge('spouse', 65, null)).toBe(65);
  });

  it('returns currentAge for self owner even when spouseAge is null', () => {
    expect(resolveOwnerAge('self', 70, null)).toBe(70);
  });
});

describe('buildStartAgeOptions', () => {
  it('builds 59 options from age 62 to 120', () => {
    const options = buildStartAgeOptions(2026, 50);
    expect(options.length).toBe(59);
    expect(options[0].value).toBe(62);
    expect(options[options.length - 1].value).toBe(120);
  });

  it('labels include age and computed year', () => {
    const options = buildStartAgeOptions(2026, 50);
    // Age 62 for a 50-year-old in 2026 → year 2038
    expect(options[0].label).toBe('62 (2038)');
    // Age 67 → year 2043
    expect(options[5].label).toBe('67 (2043)');
  });

  it('computes correct year for spouse with different age', () => {
    // Spouse is 60 in reference year 2026 → age 62 starts in 2028
    const options = buildStartAgeOptions(2026, 60);
    expect(options[0].label).toBe('62 (2028)');
  });

  it('shows past years when owner already passed the start age', () => {
    // Owner is 74 in 2026 → age 62 would have been 2014
    const options = buildStartAgeOptions(2026, 74);
    expect(options[0].label).toBe('62 (2014)');
    // Age 74 → current year
    expect(options[12].label).toBe('74 (2026)');
  });
});

describe('monthly/annual conversion logic', () => {
  it('monthly to annual: multiply by 12', () => {
    const monthlyAmount = 2000;
    const annualAmount = monthlyAmount * 12;
    expect(annualAmount).toBe(24000);
  });

  it('annual to monthly: divide by 12', () => {
    const annualAmount = 24000;
    const monthlyAmount = annualAmount / 12;
    expect(monthlyAmount).toBe(2000);
  });

  it('handles non-round monthly amounts', () => {
    const monthlyAmount = 2341;
    const annualAmount = monthlyAmount * 12;
    expect(annualAmount).toBe(28092);
    // Round-trip: annual back to monthly
    expect(annualAmount / 12).toBe(2341);
  });

  it('rounds display amount on period toggle to avoid floating point noise', () => {
    // Simulate: user enters $2500 annual, toggles to monthly
    const annual = 2500;
    const monthly = Math.round((annual / 12) * 100) / 100;
    expect(monthly).toBe(208.33);
    // Toggle back to annual
    const backToAnnual = Math.round(monthly * 12 * 100) / 100;
    expect(backToAnnual).toBe(2499.96); // small rounding difference is expected
  });

  it('re-edit restores monthly display amount from stored annual', () => {
    // User saved $2000/month → stored as $24000 annual with amountPeriod: 'monthly'
    const storedAmount = 24000;
    const storedPeriod = 'monthly';
    const displayAmount = storedPeriod === 'monthly' ? storedAmount / 12 : storedAmount;
    expect(displayAmount).toBe(2000);
  });

  it('re-edit shows annual amount when amountPeriod is annual', () => {
    const storedAmount = 30000;
    // Annual period means display amount equals stored amount (no division)
    expect(storedAmount).toBe(30000);
  });
});
